routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'manage'])->name('dashboard');

Route::get('/categories/manage', [App\Http\Controllers\CategoryController::class, 'manage']);
Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::get('/posts/manage', [App\Http\Controllers\PostController::class, 'manage']);
Route::get('/posts/reorder', [App\Http\Controllers\PostController::class, 'reorder']);
Route::resource('posts', App\Http\Controllers\PostController::class);

Route::get('/donations/manage', [App\Http\Controllers\DonationController::class, 'manage']);
Route::resource('donations', App\Http\Controllers\DonationController::class);


Route::get('/orders/manage', [App\Http\Controllers\OrderController::class, 'manage']);
Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::get('users/manage', [App\Http\Controllers\UserController::class, 'manage']);
Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('links/manage', [App\Http\Controllers\LinkController::class, 'manage']);
Route::resource('links', App\Http\Controllers\LinkController::class);

Route::get('albums/manage', [App\Http\Controllers\AlbumController::class, 'manage']);
Route::resource('albums', App\Http\Controllers\AlbumController::class);

Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact']);
Route::post('/contact',[App\Http\Controllers\HomeController::class, 'send']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Donation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Donation extends Model implements HasMedia
{
    use HasFactory;
    use InteractsWithMedia;
    protected $guarded = [];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    public function account()
    {
        return $this->belongsTo(Account::class);
    }
}

app/Http/Controllers/DonationController.php
<?php

namespace App\Http\Controllers;

use App\Models\Account;
use App\Models\Category;
use App\Models\Donation;
use Illuminate\Http\Request;
use Artesaos\SEOTools\Facades\SEOMeta;

class DonationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth')->except(['create','store']);
        $this->middleware('admin')->only(['manage','edit','update','delete']);
    }


    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function manage(Donation $donation)
    {
        return view('donations.manage', ['donations' => Donation::all()]);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        SEOMeta::setTitle(__('Donations'));
        SEOMeta::addKeyword(['Alber','المنشورات','جمعية البر','ahsaber','مساعدات','مساعدة','محتاجين'
            ,'جمع التبرعات','خيرية','دعم','تبرع','جمعية','طريقة التبرع']);

        $projects = Category::where('type',2)->get();
        $accounts = Account::all();

        return view('donations.create', compact('projects','accounts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'payment_type' => 'required',
            'date' => 'required',
            'account_id' => 'required',
            'amount' => 'required',
            'from_account' => 'nullable',
            'name' => 'required',
            'phone' => 'required',
            'category_id' => 'required',
        ]);
        $donation = Donation::create($data);
        if ($request->hasFile('image')) {
            $donation->addMediaFromRequest('image')->toMediaCollection('donations');
        }
        return redirect('home')
            ->withSuccess(__('Your donation has been created successfully'));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\donation $donation
     * @return \Illuminate\Http\Response
     */
    public function show(donation $donation)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\donation $donation
     * @return \Illuminate\Http\Response
     */
    public function edit(Donation $donation)
    {
        $projects = Category::where('type',2)->get();
        $accounts = Account::all();
        return view('donations.edit', compact('donation','projects','accounts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\donation $donation
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, Donation $donation)
    {
        $data = request()->validate([
            'payment_type' => 'required',
            'date' => 'required',
            'account_id' => 'required',
            'amount' => 'required',
            'from_account' => 'nullable',
            'name' => 'required',
            'phone' => 'required',
            'category_id' => 'required',
        ]);

        $donation->update($data);

        if ($request->hasFile('image')) {
            $donation->media()->delete($this);
            $donation->addMediaFromRequest('image')->toMediaCollection('donations');
        }

        return redirect('donations/manage');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\donation $donation
     * @return \Illuminate\Http\Response
     */
    public function destroy(Donation $donation)
    {
        $donation->delete();
        return redirect('donations/manage');

    }
}

resources/views/donations/create.blade.php
<x-layouts.base>
    @section('content')
        <x-feedback/>
        <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col m-5">
            <h1>{{__('Create').' '.__('Donation')}}</h1>

            <x-form action="{{url('donations')}}" method="post" has-files>

                <div class="-mx-3 md:flex">
                    <div class="md:w-1/2 px-3">
                        <label>{{__('type').' '.__('Payment')}}</label>
                        <x-select name="payment_type" id="payment_type"
                                  label="{{__('type').' '.__('Payment')}}">
                            <option value="1">{{__('Transfer').' '.__('Bank')}}</option>
                            <option value="2">{{__('Deposit')}}</option>
                        </x-select>
                    </div>
                    <div class="md:w-1/2 px-3">
                        <label>{{__('date').' '.__('Deposit or Bank Transfer')}}</label>
                        <x-input name="date" class="text-right" value="{{ old('date') }}" type="date"/>
                    </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-1/2 px-3">
                        <label>{{__('From Bank')}}</label>
                        <x-input name="from_account" value="{{ old('from_account') }}" type="number"/>
                    </div>
                    <div class="md:w-1/2 px-3">
                        <label>{{__('To Bank')}}</label>
                            <x-select name="account_id" id="account_id"
                                      label="{{__('To Bank')}}">
                                @foreach($accounts as $account)
                                    <option value="{{$account->id}}">{{$account->name}}</option>
                                @endforeach
                            </x-select>
                        </div>
                    </div>


                <div class="-mx-3 md:flex">
                    <div class="md:w-1/2 px-3 mb-6 md:mb-0">
                        <label>{{__('Name')}}</label>
                        <x-input name="name" value="{{ old('name') }}"/>
                    </div>
                    <div class="md:w-1/2 px-3 mb-6 md:mb-0">
                        <label>{{__('Phone')}}</label>
                        <x-input name="phone" value="{{ old('phone') }}" type="tel"/>
                    </div>
                </div>
                <div class="-mx-3 md:flex">
                    <div class="md:w-1/2 px-3">
                        <label>{{__('Project')}}</label>
                        <x-select name="category_id" id="category_id"
                                  label="{{__('Project')}}">
                            @foreach($projects as $project)
                                <option value="{{ $project->id }}">{{ $project->name }}</option>
                            @endforeach
                        </x-select>
                    </div>
                    <div class="md:w-1/2 px-3">
                        <label>{{__('Amount')}}</label>
                        <x-input name="amount" value="{{ old('amount') }}" type="number"/>
                    </div>
                </div>
                <div class="field">
                    <label class="text-lg font-extrabold leading-8 tracking-tight text-gray-800 sm:text-lg sm:leading-9"
                           for="image">{{__('Attach').' '.__('Image').' '.__('Deposit')}}</label>
                    <div class="mt-3">
                        <x-input type="file" id="image" name="image"/>
                    </div>
                </div>

                <div class="mt-5">
                    <button type="submit" class="btn">
                        {{__('Create')}}
                    </button>

                    <input type="button" class="btn-cancel"
                           name="cancel" value="{{__('Cancel')}}" onClick="window.location.replace ('/donations/manage');"/>
                </div>
            </x-form>
        </div>


    @endsection
</x-layouts.base>

resources/views/donations/edit.blade.php
<x-layouts.admin>
    <x-feedback/>
    <x-form action="{{ route('donations.update',['donation'=>$donation->id]) }}" method="PUT" has-files>
        <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col m-5">
            <div class="-mx-3 md:flex">
                <div class="md:w-1/2 px-3">
                    <label>{{__('type').' '.__('Payment')}}</label>
                    <x-select class="ml-4 select" name="payment_type" id="payment_type"
                              label="{{__('type').' '.__('Payment')}}">
                        <option value="1" {{$donation->payment_type === '1' ? "selected" : "" }}>{{__('Transfer').' '.__('Bank')}}</option>
                        <option value="2" {{$donation->payment_type === '2' ? "selected" : "" }}>{{__('Deposit')}}</option>
                    </x-select>
                </div>
                <div class="md:w-1/2 px-3">
                    <label>{{__('date').' '.__('Deposit or Bank Transfer')}}</label>
                    <x-input class="text-right" name="date" value="{{$donation->date}}" type="date"/>
                </div>
            </div>
            <div class="-mx-3 md:flex">
                <div class="md:w-1/2 px-3">
                    <label>{{__('From Bank')}}</label>
                    <x-input name="from_account" value="{{$donation->from_account}}" placeholder="{{__('From Bank')}}" type="number"/>
                </div>
                <div class="md:w-1/2 px-3">
                    <label>{{__('To Bank')}}</label>
                    <x-select class="ml-4 select" name="account_id" id="account_id"
                              label="{{__('To Bank')}}">
                        @foreach($accounts as $account)
                            <option value="{{ $account->id }}" {{$account->id == $donation->account_id  ? 'selected' : ''}}>
                                {{ $account->name }}</option>
                        @endforeach
                    </x-select>
                </div>
            </div>

            <div class="-mx-3 md:flex ">
                <div class="md:w-1/2 px-3 mb-6 md:mb-0">
                    <label>{{__('Name')}}</label>
                    <x-input name="name" value="{{$donation->name}}" placeholder="{{__('Name')}}"/>
                </div>
                <div class="md:w-1/2 px-3 mb-6 md:mb-0">
                    <label>{{__('Phone')}}</label>
                    <x-input name="phone" value="{{$donation->phone}}" placeholder="{{__('Phone')}}" type="tel"/>
                </div>
            </div>

            <div class="-mx-3 md:flex ">
                <div class="md:w-1/2 px-3">
                    <label>{{__('Project')}}</label>
                    <x-select class="ml-4 select" name="category_id" id="category_id"
                              label="{{__('Project')}}">
                        @foreach($projects as $project)
                            <option value="{{ $project->id }}"
                                    {{$project->id == $donation->category_id  ? 'selected' : ''}}>{{ $project->name }}</option>

                        @endforeach
                    </x-select>
                </div>
                <div class="md:w-1/2 px-3">
                    <label>{{__('Amount')}}</label>
                    <x-input name="amount" value="{{$donation->amount}}" placeholder="{{__('Amount')}}" type="number"/>
                </div>
            </div>

            <div class="">
                @if($donation->hasMedia('donations') )
                    @foreach($donation->getMedia('donations') as $attachment)
                        {{$attachment}}
                    @endforeach
                @endif
            </div>

            <div class="mt-5">
                <button type="submit" class="btn">
                    {{__('Edit')}}
                </button>
                <input type="button" class="btn-cancel mt-3"
                       name="cancel" value="{{__('Cancel')}}" onClick="window.location.replace('/donations/manage');"/>
            </div>
        </div>
    </x-form>

</x-layouts.admin>

resources/views/donations/manage.blade.php
<x-manage model="Donations" action="donations/create" :data="$donations" modelName="Donation">
    <div class="w-full mx-5">
        <livewire:donations-datatable/>
    </div>
</x-manage>