routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'manage'])->name('dashboard');

Route::get('/categories/manage', [App\Http\Controllers\CategoryController::class, 'manage']);
Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::get('/posts/manage', [App\Http\Controllers\PostController::class, 'manage']);
Route::get('/posts/reorder', [App\Http\Controllers\PostController::class, 'reorder']);
Route::resource('posts', App\Http\Controllers\PostController::class);

Route::get('/donations/manage', [App\Http\Controllers\DonationController::class, 'manage']);
Route::resource('donations', App\Http\Controllers\DonationController::class);


Route::get('/orders/manage', [App\Http\Controllers\OrderController::class, 'manage']);
Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::get('users/manage', [App\Http\Controllers\UserController::class, 'manage']);
Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('links/manage', [App\Http\Controllers\LinkController::class, 'manage']);
Route::resource('links', App\Http\Controllers\LinkController::class);

Route::get('albums/manage', [App\Http\Controllers\AlbumController::class, 'manage']);
Route::resource('albums', App\Http\Controllers\AlbumController::class);

Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact']);
Route::post('/contact',[App\Http\Controllers\HomeController::class, 'send']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Database\Eloquent\Builder;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Post extends Model implements HasMedia
{
    use HasFactory;
    use HasSlug;
    use InteractsWithMedia;

    protected $guarded = [];
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->slugsShouldBeNoLongerThan(50);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

//    protected static function booted()
//    {
//        static::addGlobalScope('conditions', function (Builder $builder) {
//            $builder->where('posts.slug', '<>', 'conditions');
//        });
//    }


}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Post;
use App\Models\Category;
use function React\Promise\all;
use Artesaos\SEOTools\Facades\SEOMeta;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function __construct()
    {
        $this->middleware('auth')->only(['manage','create','store','edit','update','delete']);
        $this->middleware('admin')->only(['manage','create','store','edit','update','delete']);
    }

    public function index(Request $request)
    {
        SEOMeta::setTitle(__('Posts'));
        SEOMeta::addKeyword(['Alber','المنشورات','جمعية البر','ahsaber','مساعدات','مساعدة','محتاجين'
            ,'مشاريع','خيرية','دعم','تبرع','جمعية','طريقة التبرع']);

        $categories = Category::all()->except(4);
        $posts = Post::whereIsPublished(true)
            ->where('category_id','<>','3')
            ->latest()
            ->simplePaginate(10);
        return view('posts.index', compact('posts', 'categories'));
    }


    public function manage(Post $post)
    {
        return view('posts.manage', ['posts' => Post::all()]);
    }

    public function reorder()
    {
        $posts = Post::where('category_id',3)->get();
        return view('posts.reorder', compact('posts'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('posts.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'category_id' => 'required',
            'title' => 'required',
            'body' => 'required',
            'short_description'=>'nullable',
            'is_published' => 'nullable',
            'is_featured' => 'nullable',
        ]);
        $post = Post::create($data);

        if ($request->hasFile('image')) {
            $post->addMediaFromRequest('image')->toMediaCollection('posts');
        }

        return redirect('posts/manage')
            ->with('success', 'Your Post has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        SEOMeta::setTitle($post->title);
        SEOMeta::addKeyword(['Alber','منشور','المنشورات','جمعية البر','ahsaber','مساعدات','مساعدة','محتاجين'
            ,'خيرية','دعم','تبرع','جمعية']);

        $posts = Post::with('category')->get();

        return view('posts.show', compact('post','posts'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        $categories = Category::all();
        return view('posts.edit', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, Post $post)
    {
        $data = request()->validate([
            'category_id' => 'required',
            'title' => 'required',
            'body' => 'required',
            'short_description'=>'nullable',
            'is_published' => 'nullable',
            'is_featured' => 'nullable',
        ]);

        $post->update($data);
        if ($request->hasFile('image')) {
            $post->media()->delete($this);
            $post->addMediaFromRequest('image')->toMediaCollection('posts');
        }

        return redirect('posts/manage');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect('posts/manage');

    }
}

resources/views/posts/create.blade.php
<x-layouts.admin>
    <x-feedback/>

    <h1>{{__('Create').' '.__('post')}}</h1>

    <x-form action="{{url('posts')}}" method="post" has-files>
        <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col my-2">
            <div class="-mx-3 md:flex mb-6">
                <div class="md:w-1/2 px-3 mb-3 md:mb-0">
                    <label class="mb-3">{{__('Title')}}</label>
                    <x-input name="title" value="{{ old('title') }}" placeholder="{{__('Title')}}"/>
                </div>
                <div class="md:w-1/2 px-3">
                    <label class="mb-3">{{__('type').' '.__('Post')}}</label>
                    <x-select class="ml-4 select" name="category_id" id="category"
                              label="{{__('type').' '.__('Post')}}">
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </x-select>
                </div>
            </div>
            <label class="mb-3">{{__('description').' '.__('Post')}}</label>
            <x-summernote name="body" default=""/>

            <label class="mb-3">{{__('description').' '.__('Short')}}</label>
            <x-input name="short_description" value="{{ old('short_description') }}"
                     placeholder="{{__('description').' '.__('Short')}}"/>

            <div class="field mb-5">
                <label class="text-lg font-extrabold leading-8 tracking-tight text-gray-800 sm:text-lg sm:leading-9"
                       for="image">{{__('Add Main image for the Post')}}</label>
                <div class="mt-3">
                    <x-input class="input" type="file" id="image" name="image"/>
                </div>
            </div>

            <div class="flex mt-3">
                <x-cb name="is_published" label="Is Published" default=""/>
                <x-cb name="is_featured" label="Is Featured" default=""/>
            </div>
            <div class="mt-3">
                <button type="submit" class="btn">
                    {{__('Create')}}
                </button>
                <input type="button" class="btn-cancel mt-3"
                       name="cancel" value="{{__('Cancel')}}" onClick="window.location.replace('/posts/manage');"/>
            </div>
        </div>
    </x-form>


</x-layouts.admin>

resources/views/posts/edit.blade.php
<x-layouts.admin>
    <x-feedback/>
    <h1>{{__('Edit').' '.__('post'). ": $post->title"}}</h1>
    <x-form action="{{ route('posts.update',['post'=>$post->slug]) }}" method="PUT" has-files>
        <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col my-2">
            <div class="-mx-3 md:flex mb-6">
                <div class="md:w-1/2 px-3 mb-3 md:mb-0">
                    <label class="mb-3">{{__('Title')}}</label>
                    <x-input name="title" value="{{$post->title}}" placeholder="{{__('Title')}}"/>
                </div>
                <div class="md:w-1/2 px-3">
                    <label class="mb-3">{{__('type').' '.__('Post')}}</label>
                    <x-select class="ml-4 select" name="category_id" id="category"
                              label="{{__('type').' '.__('Post')}}">
                        @foreach($categories as $category)
                            <option value="{{ $category->id }}" {{$category->id == $post->category_id  ? 'selected' : ''}}>
                                {{ $category->name }}</option>
                        @endforeach
                    </x-select>
                </div>
            </div>
            <label>{{__('description').' '.__('Post')}}</label>
            <x-summernote name="body" :default="$post->body"/>

            <label>{{__('description').' '.__('Short')}}</label>
            <x-input name="short_description" value="{{ $post->short_description }}"
                     placeholder="{{__('description').' '.__('Short')}}"/>

            <div class="field text-right ">
                <div>
                    @if($post->hasMedia('posts') )
                        <div class="object-cover mb-5">
                            @foreach($post->getMedia('posts') as $attachment)
                                <div class="h-25 w-25">
                                    {{$attachment}}
                                </div>
                            @endforeach
                        </div>
                    @endif
                </div>

                <div class="field mb-5">
                    <label for="image">{{__('Edit Main image for the Post')}}</label>
                    <div class="mt-3">
                        <x-input type="file" id="image" name="image"/>
                    </div>
                </div>
            </div>

            <div class="flex my-5">
                <x-cb name="is_published" label="Is Published" :default="$post->is_published"/>
                <x-cb name="is_featured" label="Is Featured" :default="$post->is_featured"/>
            </div>
            <div class="mt-3">
                <button type="submit" class="btn">
                    {{__('Edit')}}
                </button>
                <input type="button" class="btn-cancel"
                       name="cancel" value="{{__('Cancel')}}" onClick="window.location.replace('/posts/manage');"/>
            </div>
        </div>
    </x-form>

</x-layouts.admin>

resources/views/posts/index.blade.php
@extends('components.layouts.app')

@section('content')
    <div class="mt-10">
        <h1 class="w-full my-2 text-5xl font-bold leading-tight text-center text-gray-800">
            {{__('articles')}}</h1>
        <div class="w-full mb-4">
            <div class="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t bg-green-900"></div>
        </div>
        <div class="mx-auto">
            <div class="m-2">
                @foreach( $posts as $featuredPost)
                    <div class="bg-white rounded-xl lg:m-10 mb-3">
                        <x-cards.post :post="$featuredPost"/>
                    </div>
                @endforeach
            </div>
            <div class="flex justify-center my-1">
                <snap>{{ $posts->links()}}</snap>
            </div>
        </div>
    </div>
@endsection

resources/views/posts/manage.blade.php
<x-manage model="Posts" action="posts/create" :data="$posts" modelName="Post">
    <div class="w-full mx-5">
        <livewire:posts-datatable/>
    </div>
</x-manage>

resources/views/posts/reorder.blade.php
<x-layouts.admin>
    <div class="drag-and-drop">
        <div class="drag-and-drop__container drag-and-drop__container--from">
            <h3 class="drag-and-drop__title">{{__('Order').' '.__('Posts')}}</h3>

            <ul>
                @foreach($posts as $post)
                <li>{{$post->order}}  {{$post->title}} <a class='up' href='#'>up</a> <a class='down' href='#'>down</a></li>
                @endforeach
                <li class="count">i <a class='up' href='#'>up</a> <a class='down' href='#'>down</a></li>
                <li>3 <a class='up' href='#'>up</a> <a class='down' href='#'>down</a></li>
                <li>4 <a class='up' href='#'>up</a> <a class='down' href='#'>down</a></li>
                <li>5 <a class='up' href='#'>up</a> <a class='down' href='#'>down</a></li>
                <li>6 <a class='up' href='#'>up</a> <a class='down' href='#'>down</a></li>
            </ul>

            {{--<ul class="drag-and-drop__items" id="list">--}}
                {{--<!-- loop through the items -->--}}
                {{--@foreach($posts as $post)--}}
                    {{--<li id="{{$post->id}}" class="li">--}}
                        {{--<a  class=" mt-8"--}}
                                {{--@click="up()">{{__('Up')}}</a>--}}
                        {{--<p>{{$post->title}}</p><p>{{$post->order}}</p>--}}
                        {{--<a  class=" mt-8"--}}
                                {{--@click="down()">{{__('Down')}}</a>--}}
                    {{--</li>--}}
                {{--@endforeach--}}
            {{--</ul>--}}
        </div>
    </div>
    <script>
        window.onload = function () {
            var upLink = document.querySelectorAll(".up");
            var count = 0;
            for (var i = 0; i < upLink.length; i++) {
                upLink[i].addEventListener('click', function () {
                    var wrapper = this.parentElement;


                    if (wrapper.previousElementSibling)
                        wrapper.parentNode.insertBefore(wrapper, wrapper.previousElementSibling);
                });
            }

            var downLink = document.querySelectorAll(".down");

            for (var i = 0; i < downLink.length; i++) {
                downLink[i].addEventListener('click', function () {
                    var wrapper = this.parentElement;

                    if (wrapper.nextElementSibling)
                        wrapper.parentNode.insertBefore(wrapper.nextElementSibling, wrapper);
                });
            }

            document.getElementsByClassName('count').innerHTML = 'it is '+count;
        }
    </script>

</x-layouts.admin>

resources/views/posts/show.blade.php
<x-layouts.app>
    <div class="m-5 w-full">

        <div class="lg:p-6 pl-3">
            <div class="object-contain lg:w-80 md:w-72 ml-auto mr-auto block ">
                @foreach($post->getMedia('posts') as $attachment)
                    {{$attachment}}
                @endforeach
            </div>
            <h1 class="mt-3">{{$post->title}}</h1>
            <p class="mt-3 text-base leading-6 text-gray-500 pl-3 text-justify">
                {!!$post->body!!}
            </p>

            <div class="flex">
                <p class="mt-3 text-base leading-6 text-gray-900 ml-2">
                    {{__('Type')}}:
                </p>
                <p class="mt-3 text-base leading-6 text-green-800">
                    {{$post->category->name}}
                </p>
            </div>

            <div class="text-sm mt-3 leading-5 text-gray-500">
                {{__('Publish Date')}}: {{$post->created_at->toDateString()}}
            </div>

        </div>

    </div>
</x-layouts.app>