routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'manage'])->name('dashboard');

Route::get('/categories/manage', [App\Http\Controllers\CategoryController::class, 'manage']);
Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::get('/posts/manage', [App\Http\Controllers\PostController::class, 'manage']);
Route::get('/posts/reorder', [App\Http\Controllers\PostController::class, 'reorder']);
Route::resource('posts', App\Http\Controllers\PostController::class);

Route::get('/donations/manage', [App\Http\Controllers\DonationController::class, 'manage']);
Route::resource('donations', App\Http\Controllers\DonationController::class);


Route::get('/orders/manage', [App\Http\Controllers\OrderController::class, 'manage']);
Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::get('users/manage', [App\Http\Controllers\UserController::class, 'manage']);
Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('links/manage', [App\Http\Controllers\LinkController::class, 'manage']);
Route::resource('links', App\Http\Controllers\LinkController::class);

Route::get('albums/manage', [App\Http\Controllers\AlbumController::class, 'manage']);
Route::resource('albums', App\Http\Controllers\AlbumController::class);

Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact']);
Route::post('/contact',[App\Http\Controllers\HomeController::class, 'send']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Album.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Album extends Model implements HasMedia
{
    use HasFactory;
    use HasSlug;
    use InteractsWithMedia;
    protected $guarded = [];

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->slugsShouldBeNoLongerThan(50);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/AlbumController.php
<?php

namespace App\Http\Controllers;

use App\Models\Album;
use Illuminate\Http\Request;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
    }

    public function index()
    {


    }

    public function manage()
    {
        return view('albums.manage', ['albums' => Album::all()]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('albums.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'title' => 'required',
        ]);
        $album = Album::create($data);

        if ($request->hasFile('image')) {
            $album->addMediaFromRequest('image')->toMediaCollection('albums');
        }
        return redirect('albums/manage')
            ->with('success', 'Your Post has been created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function show(Album $album)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function edit(Album $album)
    {
        return view('albums.edit', compact('album'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Album $album)
    {
        $data = request()->validate([
            'title' => 'required',
        ]);

        $album->update($data);

        if ($request->hasFile('image')) {
            $album->media()->delete($this);
            $album->addMediaFromRequest('image')->toMediaCollection('albums');
        }

        return redirect('albums/manage');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Album  $album
     * @return \Illuminate\Http\Response
     */
    public function destroy(Album $album)
    {
        $album->delete();

        return redirect('albums/manage');
    }
}

resources/views/albums/create.blade.php
<x-layouts.admin>
    <x-feedback/>

    <h1>{{__('Create').' '.__('album')}}</h1>

    <div class="mx-3 text-right">

        <x-form action="{{url('albums')}}" method="post" has-files>
            @csrf
            <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col my-2">

                <div class="-mx-3 md:flex mb-6">
                    <div class="md:w-1/2 px-3 mb-3 md:mb-0">
                        <label class="mb-3">{{__('title').' '.__('Album')}}</label>
                        <x-input name="title" value="{{ old('title') }}" placeholder="{{__('title')}}"/>
                    </div>
                </div>

                <div class="field mb-5">
                    <label class="text-lg font-extrabold leading-8 tracking-tight text-gray-800 sm:text-lg sm:leading-9"
                           for="image">{{__('Add').' '.__('Images').' '.__('Album')}}</label>
                    <div class="mt-3">
                        <x-input class="input" type="file" id="image" name="image" required/>
                    </div>
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn">
                        {{__('Create')}}
                    </button>
                    <input type="button" class="btn-cancel mt-3"
                           name="cancel" value="{{__('Cancel')}}" onClick="window.location.replace('/albums/manage');"/>
                </div>
            </div>
        </x-form>
    </div>
</x-layouts.admin>

resources/views/albums/edit.blade.php
<x-layouts.admin>
    <x-feedback/>

    <div class="mx-2 text-right">

        <x-form action="{{ route('albums.update',['album'=>$album->slug]) }}" method="PUT" has-files>
            @csrf
            <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col my-2">
                <div class="-mx-3 md:flex mb-6">
                    <div class="md:w-1/2 px-3 mb-3 md:mb-0">
                        <label class="mb-3">{{__('title').' '.__('Album')}}</label>
                        <x-input name="title" value="{{$album->title}}" placeholder="{{__('title')}}"/>
                    </div>
                </div>
                <div class="field mb-5">
                    <label class="text-lg font-extrabold leading-8 tracking-tight text-gray-800 sm:text-lg sm:leading-9"
                           for="image">{{__('Edit').' '.__('Images').' '.__('Album')}}</label>
                    <div class="w-64 ml-auto mr-auto block lg:m-10 md:grid md:gap-6 md:grid-cols-3">
                        @if($album->hasMedia('albums') )
                            @foreach($album->getMedia('albums') as $attachment)
                                {{$attachment}}
                            @endforeach
                        @endif
                    </div>
                    <div class="mt-3">
                        <x-input class="input" type="file" id="image" name="image" required>
                    </div>
                </div>
                <div class="mt-3">
                    <button type="submit" class="btn mt-3">{{__('Edit')}}</button>

                    <input type="button" class="btn-cancel mt-3"
                           name="cancel" value="{{__('Cancel')}}"
                           onClick="window.location.replace('/albums/manage');"/>
                </div>
            </div>
        </x-form>

    </div>

</x-layouts.admin>

resources/views/albums/manage.blade.php
<x-manage model="Albums" action="albums/create" :data="$albums" modelName="Album">
    <div class="w-full mx-5">
        <livewire:albums-datatable/>
    </div>

</x-manage>