routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', [App\Http\Controllers\HomeController::class, 'manage'])->name('dashboard');

Route::get('/categories/manage', [App\Http\Controllers\CategoryController::class, 'manage']);
Route::resource('categories', App\Http\Controllers\CategoryController::class);

Route::get('/posts/manage', [App\Http\Controllers\PostController::class, 'manage']);
Route::get('/posts/reorder', [App\Http\Controllers\PostController::class, 'reorder']);
Route::resource('posts', App\Http\Controllers\PostController::class);

Route::get('/donations/manage', [App\Http\Controllers\DonationController::class, 'manage']);
Route::resource('donations', App\Http\Controllers\DonationController::class);


Route::get('/orders/manage', [App\Http\Controllers\OrderController::class, 'manage']);
Route::resource('orders', App\Http\Controllers\OrderController::class);


Route::get('users/manage', [App\Http\Controllers\UserController::class, 'manage']);
Route::resource('users', App\Http\Controllers\UserController::class);

Route::get('links/manage', [App\Http\Controllers\LinkController::class, 'manage']);
Route::resource('links', App\Http\Controllers\LinkController::class);

Route::get('albums/manage', [App\Http\Controllers\AlbumController::class, 'manage']);
Route::resource('albums', App\Http\Controllers\AlbumController::class);

Route::get('/contact', [App\Http\Controllers\HomeController::class, 'contact']);
Route::post('/contact',[App\Http\Controllers\HomeController::class, 'send']);

Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Spatie\Sluggable\HasSlug;
use Spatie\Sluggable\SlugOptions;

class Order extends Model
{
    use HasFactory;
    use HasSlug;
    protected $guarded = [];
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getSlugOptions(): SlugOptions
    {
        return SlugOptions::create()
            ->generateSlugsFrom('title')
            ->saveSlugsTo('slug')
            ->slugsShouldBeNoLongerThan(50);
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin')->only(['manage','edit','update','delete']);
    }


    public function index()
    {
        //
    }
    public function manage()
    {
        return view('orders.manage', ['orders' => Order::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('orders.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = request()->validate([
            'title' => 'required',
            'problem' => 'required',
            'address' => 'required',
            'device'=>'required',
            'type' => 'required',
        ]);
        $data['user_id'] = auth()->id();
        Order::create($data);//->user()->id;

        return redirect('home')
            ->withSuccess(__('Your order has been created successfully'));
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        return view('orders.show', compact('order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('orders.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $data = request()->validate([
            'title' => 'required',
            'problem' => 'required',
            'address' => 'required',
            'device'=>'required',
            'type' => 'required',
            'state'=>'required',
            'notes'=>'nullable'
        ]);
        $order->update($data);

        return redirect('orders/manage');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();
        return redirect('orders/manage');
    }
}

resources/views/orders/create.blade.php
<x-layouts.base>
    @section('content')
        <x-feedback/>
        <div class="bg-white shadow-lg rounded flex flex-col m-5 pt-5">

            <x-form action="{{url('orders')}}" method="post" has-files>
                <div class="md:m-10 m-5">
                    <h1>{{__('Create').' '.__('order')}}</h1>
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="label">{{__('Title')}}</label>
                        <x-input name="title" value="{{ old('title') }}"/>
                    </div>
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="label">{{__('Problem')}}</label>
                        <x-input name="problem" value="{{ old('problem') }}"/>
                    </div>
                    <div class="px-3 mb-6 md:mb-0">
                        <label class="label">{{__('Device')}}</label>
                        <x-input name="device" value="{{ old('device') }}"/>
                    </div>
                    <div class=" px-3">
                        <label class="label">{{__('type').' '.__('Order')}}</label>
                        <x-select class="ml-4 select" name="type" id="type"
                                  label="{{__('type').' '.__('Order')}}">
                            <option value="1">{{__('New')}}</option>
                            <option value="2">{{__('Maintenance')}}</option>
                        </x-select>
                    </div>
                    <div class=" px-3 mb-6 md:mb-0">
                        <label class="label">{{__('Address')}}</label>
                        <x-input name="address" value="{{ old('address') }}"/>
                    </div>
                    <div class="px-3 mb-6 md:mb-0">
                        <button type="submit" class="btn">
                            {{__('Create')}}
                        </button>
                        <input type="button" class="btn-cancel"
                               name="cancel" value="{{__('Cancel')}}"
                               onClick="window.location.replace('/home');"/>
                    </div>
                </div>
            </x-form>
        </div>
    @endsection
</x-layouts.base>

resources/views/orders/edit.blade.php
<x-layouts.admin>
    <x-feedback/>
    <h1>{{__('Edit')}}</h1>
    <x-form action="{{ route('orders.update',['order'=>$order->slug]) }}" method="PUT" has-files>
        <div class="bg-white shadow-lg rounded px-8 pt-6 pb-8 mb-4 flex flex-col my-2  print-area">
            <label>{{__('Title')}}</label>
            <x-input name="title" value="{{$order->title}}" placeholder="{{__('Title')}}"/>

            <label>{{__('Problem')}}</label>
            <x-input name="problem" value="{{$order->problem}}" placeholder="{{__('Problem')}}"/>

            <label>{{__('Device')}}</label>
            <x-input name="device" value="{{$order->device}}" placeholder="{{__('Device')}}"/>

            <label class="label">{{__('type').' '.__('Order')}}</label>
            <x-select class="ml-4 select" name="type" id="type"
                      label="{{__('type').' '.__('order')}}">
                <option value="1" {{$order->type === '1' ? "selected" : "" }}>{{__('New')}}</option>
                <option value="2" {{$order->type === '2' ? "selected" : "" }}>{{__('Maintenance')}}</option>
            </x-select>

            <label>{{__('Address')}}</label>
            <x-input name="address" value="{{$order->address}}" placeholder="{{__('Address')}}"/>

            <label class="label">{{__('state').' '.__('Order')}}</label>
            <x-select class="ml-4 select" name="state" id="state"
                      label="{{__('state').' '.__('order')}}">
                <option value="1" {{$order->state === '1' ? "selected" : "" }}>{{__('New')}}</option>
                <option value="2" {{$order->state === '2' ? "selected" : "" }}>{{__('In Progress')}}</option>
                <option value="3" {{$order->state === '3' ? "selected" : "" }}>{{__('Closed')}}</option>
                <option value="4" {{$order->state === '4' ? "selected" : "" }}>{{__('Rejected')}}</option>
            </x-select>

            <label>{{__('Notes')}}</label>
            <textarea row="4"
                      class="w-full h-40 px-5 py-3 border border-gray-400 rounded-lg outline-none focus:shadow-outline"
                      name="notes">{{$order->notes}}</textarea>

            <div class="mt-3">
                <button type="submit" class="btn">
                    {{__('Edit')}}
                </button>
                <button type="submit" class="btn" onclick="myFunction()">
                    {{__('Print')}}
                </button>
                <input type="button" class="btn-cancel"
                       name="cancel" value="{{__('Cancel')}}" onClick="window.location.replace('/orders/manage');"/>
            </div>
        </div>
    </x-form>
    <script>
        function myFunction() {
            window.print();
        }
    </script>
</x-layouts.admin>

resources/views/orders/manage.blade.php
<x-manage model="orders" action="orders/create" :data="$orders" modelName="Order">
    <div class="w-full mx-5 print-area">
        <livewire:orders-datatable/>
    </div>
</x-manage>

resources/views/orders/show.blade.php
<x-layouts.app>
    <div class="m-5 w-full">

        <h1>{{$order->title}}</h1>
        <div class="flex">
            <p class="mt-3 text-base leading-6 text-gray-900 ml-2">
                {{__('Problem')}}:
            </p>
            <p class="mt-3 text-base leading-6 text-gray-500 pl-3 text-justify">
                {{$order->problem}}
            </p>
        </div>
        <div class="flex">
            <p class="mt-3 text-base leading-6 text-gray-900 ml-2">
                {{__('Device')}}:
            </p>
            <p class="mt-3 text-base leading-6 text-gray-500 pl-3 text-justify">
                {{$order->device}}
            </p>
        </div>
        <div class="flex">
            <p class="mt-3 text-base leading-6 text-gray-900 ml-2">
                {{__('Type')}}:
            </p>
            <p class="mt-3 text-base leading-6 text-gray-500 pl-3 text-justify">
                {{$order->type}}
            </p>
        </div>
        <div class="flex">
            <p class="mt-3 text-base leading-6 text-gray-900 ml-2">
                {{__('Address')}}:
            </p>
            <p class="mt-3 text-base leading-6 text-gray-500 pl-3 text-justify">
                {{$order->address}}
            </p>
        </div>

        <div class="flex">
            <p class="mt-3 text-base leading-6 text-gray-900 ml-2">
                {{__('Publish Date')}}:
            </p>

            <div class="text-sm mt-3 leading-5 text-gray-500">
                {{$order->created_at->toDateString()}}
            </div>
        </div>
    </div>
</x-layouts.app>